### ISSUE TITLE
springSyncServiceContacts builddb ant target not working

### ISSUE THREAD

**Issue by ghost** [wileyenterpriseandroid/Examples#2]
This project is not working correctly
https://github.com/wileyenterpriseandroid/Examples/tree/master/springSyncServiceContacts

$ ant builddb
fails with

deployHBSchema:
      [sql] Executing resource: /home/oscarvarto/gitRepos/enterpriseAndroidExamples/springSyncServiceContacts/contact.hb.sql
      [sql] Failed to execute:   create table contact_sync_hbm ( id varchar(255) not null auto_increment, deleted bit not null, email varchar(255), firstName varchar(255) not null, lastName varchar(255) not null, phone varchar(255), updateTime bigint not null, version bigint not null, primary key (id) )
      [sql] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Incorrect column specifier for column 'id'
      [sql] Failed to execute:   create index updateTimeIndex on contact_sync_hbm (updateTime)
      [sql] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'springSyncContact.contact_sync_hbm' doesn't exist
      [sql] 0 of 2 SQL statements executed successfully

deployJdbcSchema:
     [echo]   jdbc.url = jdbc:mysql://localhost:3306/springSyncContact?characterEncoding=UTF-8" 
      [sql] Executing resource: /home/oscarvarto/gitRepos/enterpriseAndroidExamples/springSyncServiceContacts/contact.jdbc.sql
      [sql] Failed to execute:   create index updateTimeIndex on contact (updateTime)
      [sql] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'springSyncContact.contact' doesn't exist
      [sql] Failed to execute:  create index firstNameIndex on contact (firstName)
      [sql] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'springSyncContact.contact' doesn't exist
      [sql] 1 of 3 SQL statements executed successfully

First error might be because a varchar cannot have auto_increment. This
   id varchar(255) not null auto_increment
is generated by 
https://github.com/wileyenterpriseandroid/Examples/blob/master/springSyncServiceContacts/build-db.xml#L22
(I think).

If I commented lines 23-28 from the above file, I was able to avoid the error. However, I don't think that's the correct way to solve the problem.

I have spent several hours trying to make the example work, and this definitely makes learning much more difficult (I would expect working & correct code examples).

I tried with
- java 7
- mysql 5.6.21 on Mac OS X  / mariadb 10.0.14 on Arch Linux
- tomcat 7
- ant 1.9.4

PLEASE, HELP! I do need to learn from your book!

**Comment by ldornin** [comment]
Oscar,

Thanks for trying the project, I assure you we have tested the current code... unfortunately only on windows. I do see the same problem you do when I run on OSX. If you look at the chapter README in springSyncServiceContacts/README, you'll see that we do stipulate mysql 5.7, which implies running on another OS like windows (which we anticipated most readers would want). Since you had the wisdom to use a reasonable OS, we certainly dont want to punish you for that and we'll get the SQL ported to 5.6 ASAP, and will notify you when its ready. If you end up making a fix and want to push it to the repo, we would be happy with that route as well. We'll try to fix it today or tomorrow.  

Please know that you we are here to help with any questions you may have about other chapters and will try to get back quickly on those as well.  I do hope that you get a chance to try out the example for chapter 10.

What specifically are you hoping to learn? Maybe I can help with pointers to that as well.

--Laird

**Comment by ghost** [comment]
Last week I got rid of my Windows 8.1 installation in my laptop and installed Arch Linux on it. For me it is a pain to develop in Windows. I guess there are a lot of developers that also prefer a Unix-like environment.

I am very happy to know that you are willing to answer questions. Right now, I am reading this
http://www.amazon.com/Just-Hibernate-Madhusudhan-Konda/dp/1449334377/ref=sr_1_1?s=books&ie=UTF8&qid=1412802948&sr=1-1&keywords=just+hibernate
to try to solve the problem myself.
Basically, I am trying to learn how to avoid the auto_increment in the generated sql for
id varchar(255) not null auto_increment
(that's only for the first error).

I depend on accurate learning material to train myself. I appreciate your efforts to produce a top quality book, together with working sample code. I know that is not easy.

I am using a considerable amount of time to go through your book and code samples. I am studying it (not just reading it) and I am completely serious about it.

Thanks!

**Comment by ghost** [comment]
Hello!
I did some small changes to fix the problem. Please confirm if that is correct or not.

Annotations taken from Hibernate documentation here:
http://docs.jboss.org/hibernate/orm/3.6/reference/en-US/html/mapping.html#mapping-declaration-id
**Section 5.1.2.2. Identifier generator**
(I checked documentation for version 3.6.10.Final, because of this line of ivy.xml
<dependency org="org.hibernate" name="hibernate-entitymanager" rev="3.6.10.Final"/>

https://github.com/wileyenterpriseandroid/Examples/blob/master/springSyncServiceContacts/src/com/enterpriseandroid/springServiceContacts/dataModel/Contact.java#L21

``` java
  @Id
  // Instead of @GeneratedValue(strategy=GenerationType.AUTO)
  @GeneratedValue(generator="system-uuid")
  @GenericGenerator(name="system-uuid", strategy="uuid")
  private String id;
```

https://github.com/wileyenterpriseandroid/Examples/blob/master/springSyncServiceContacts/contact.jdbc.sql#L14-L15

``` sql
create index updateTimeIndex on contact_sync (updateTime);
create index firstNameIndex on contact_sync (firstName);
```

After this changes, $ ant builddb doesn't complain about errors. I haven't tested (yet) the whole thing to see if it works.

**Comment by ldornin** [comment]
My co-author points out that mysql 5.7 _IS_ available for MacOS, just click the "development" tab in the download area. Appreciate if you would see if this makes the problem go away.  Thanks...

**Comment by bmeike** [comment]
oscarvarto,
  If you want to fork this and then submit a pull request. we'll merge your code.

**Comment by ghost** [comment]
Hello again!

I've been working on this TWO FULL days. 

Today I struggled with MySQL 5.7.5 installation. 
I tried the DMG file from the download page, and I couldn't get rid of this error while trying to run $mysql.server start
ERROR! The server quit without updating PID file
(I had version 5.6.21 installed from homebrew, after uninstalling, everything I tried was not useful).

After that I tried to modify the homebrew formula to install newest development version 5.7.5. But I got stuck because of dependency errors (I've been chasing error after error).

The small modifications to your source code I did do not seem to work. If I try to use curl to do a POST request, then I get a 400 Status response. But the same POST request works for 
   springServiceContacts
that uses Long instead of String for the type of the ID.

TWO complete days. I've tried everything I been able...

Please, help! I'm exhausted.

**Comment by bmeike** [comment]
Hey Oscar,
  I'm really sorry to hear this isn't working out so well.  We try pretty hard to test our stuff in a bunch of  environments, as we release it.  We appear to have missed OSX.

Laird is trying to backport this to the older version of MySQL but there is just no guarantee that he'll get that done in time to be useful to you.

-blake

**Comment by zpqan** [comment]
Hi Oscar,

Sorry for taking so long to get back to you on this. 
Please remove the "@GeneratedValue" annotation from the Contact.java. 

The fixes has been checked in to the repository. Please let me know if it works for you.

Zane

**Comment by ghost** [comment]
Hello :)

Thanks for helping me. I want to tell you that I just synchronized my Nexus 7 with the server you programmed (and that I installed in my iMac).

Will continue next week (maybe I will have more questions).

**Comment by bmeike** [comment]
Congratulations, Oscar!

If you have changes to contribute, please do fork the repo and submit a pull request.  We'd love to have your contributions.

**Comment by bmeike** [comment]
Closing

**Comment by ldornin** [comment]
Oscar,

Out of curiosity, did you buy a copy of the book?  If you like it, and think we were helpful, we'd be completely grateful if you would give us a solid review on amazon:

http://www.amazon.com/Enterprise-Android-Programming-Database-Applications/dp/1118183495/ref=sr_1_1?ie=UTF8&qid=1413572631&sr=8-1&keywords=enterprise+android
